### ISSUE TITLE
Use cron expressions in EC2 Image Builder

### ISSUE THREAD

**Issue by ammo-26** [awsdocs/ec2-image-builder-user-guide#6]
### Issue

The contents of this guide [Use cron expressions in EC2 Image Builder](https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-cron.html) is providing conflicting information.

For example, using the examples provided (format: AWS console/CloudFormation):

- 0 10 * * ? / cron(0 10 * * ?)
- 0 8 1 * ? / cron(0 8 1 * ?)
- 15 12 * * ? / cron(15 12 * * ?)

Returns the error for EC2 Image Builder in the AWS console and CloudFormation respectively:
 - `The value supplied for parameter 'schedule.scheduleExpression' is not valid. Non-standard cron expressions are not supported. `
- `InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Non-standard cron expressions are not supported.`

### Working Solution

Using an online tool such as [Crontab](https://crontab.guru) invalidates the examples above. The values beneath actually work for EC2 Image Builder in the AWS console and CloudFormation:

- 0 10 * * * / cron(0 10 * * *)
- 0 8 1 * * / cron(0 8 1 * *)
- 15 12 * * * / cron(15 12 * * *)

It seems the wildcard (?) is the common denominator.

**Comment by lindseyspirit** [comment]
Thank you for bringing this to our attention. I am updating on the website documentation as well as the github file.
